package com.ocp.ocp_finalproject.audit.enums;

public enum AuditAction {
    USER_LOGOUT,
    WORKFLOW_CREATE,
    WORKFLOW_UPDATE,
    WORKFLOW_STATUS_CHANGE,
    ADMIN_USER_SUSPEND,
    WEBHOOK_KEYWORD_SELECT_RESULT,
    WEBHOOK_PRODUCT_SELECT_RESULT,
    WEBHOOK_CONTENT_GENERATE_RESULT,
    WEBHOOK_BLOG_UPLOAD_RESULT
}
